apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow

on:
  workflow_dispatch: 
    inputs:
      manifest:
        type: string
        required: true
      

jobs:
  app1:
    if: ${{ fromJSON(inputs.manifest)['prod-python-hello-world'].deploy }}
    uses: cbp-test-prod/prod-python-hello-world/.cloudbees/workflows/deploy.yaml
    with:
      artifact-id: ${{ fromJSON(inputs.manifest)['prod-python-hello-world']['cbpautomation/python-hello-world-docker'].id }}
      environment: PROD